const EXCEPTION_CODE = {
  BAD_USER_INPUT: 'BAD_USER_INPUT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT_FOUND',
  INPUT_VALIDATION_ERROR: 'INPUT_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

type ExceptionCode = keyof typeof EXCEPTION_CODE;

export { EXCEPTION_CODE, ExceptionCode };
